# ubuntu-24_04-nodejs.yml
include:
  - local: pipelines/build-multiarch-image-template.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'  # Manual trigger
      when: always
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'  # Push to main
      when: always
    - changes:
        - $DOCKERFILE_PATH
        - pipelines/ubuntu-24_04-nodejs.yml
      when: always


stages:
  - build
  - packaging



# Build for linux/amd64
build-ubuntu-24_04-nodejs-amd64:
  extends: .build-amd64
  variables:
    DOCKERFILE_PATH: ubuntu-24_04/Dockerfile-Nodejs
    IMAGE_NAME: gitlab-pipeline-ubuntu-nodejs
    IMAGE_VERSION: '24.04'
    HARBOR_PROJECT: dev-tools
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'  # Manual trigger
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'  # Push to main
      when: manual
    - changes:
        - $DOCKERFILE_PATH
        - pipelines/ubuntu-24_04-nodejs.yml
      when: manual

# Build for linux/arm64
build-ubuntu-24_04-nodejs-arm64:
  extends: .build-arm64
  variables:
    DOCKERFILE_PATH: ubuntu-24_04/Dockerfile-Nodejs
    IMAGE_NAME: gitlab-pipeline-ubuntu-nodejs
    IMAGE_VERSION: '24.04'
    HARBOR_PROJECT: dev-tools
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'  # Manual trigger
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'  # Push to main
      when: manual
    - changes:
        - $DOCKERFILE_PATH
        - pipelines/ubuntu-24_04-nodejs.yml
      when: manual

# Create and push manifest
build-ubuntu-24_04-nodejs-create-manifest:
  extends: .create-manifest
  variables:
    DOCKERFILE_PATH: ubuntu-24_04/Dockerfile-Nodejs
    IMAGE_NAME: gitlab-pipeline-ubuntu-nodejs
    IMAGE_VERSION: '24.04'
    HARBOR_PROJECT: dev-tools
  stage: packaging
  needs:
    - job: build-ubuntu-24_04-nodejs-amd64
      artifacts: false
    - job: build-ubuntu-24_04-nodejs-arm64
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'  # Manual trigger
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'  # Push to main
      when: manual
    - changes:
        - $DOCKERFILE_PATH
        - pipelines/ubuntu-24_04-nodejs.yml
      when: manual
