# ubuntu-22_04-nodejs.yml
include:
  - local: pipelines/build-image-template.yml

workflow:
  rules:
    # - if: '$CI_PIPELINE_SOURCE == "web"'  # Manual trigger
    #   when: manual
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'  # Push to main
    # - if: '$CI_PIPELINE_SOURCE == "push"'  # Push to main
      when: always

stages:
  - build

# Job using the template for Ubuntu 22.04
.build-ubuntu-22_04-nodejs:
  extends: .build-image-template
  variables:
    DOCKERFILE_PATH: ubuntu-22_04/Dockerfile-Nodejs
    PLATFORMS: linux/amd64,linux/arm64
    IMAGE_NAME: gitlab-pipeline-ubuntu-nodejs
    IMAGE_VERSION: '22.04'
    HARBOR_PROJECT: dev-tools
  rules:
    - changes:
        - pipelines/ubuntu-22_04-nodejs.yml
      when: always
